from enum import Enum

class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_FOR_SONAR = "WAITING_FOR_SONAR"
    FETCHING_RESULTS = "FETCHING_RESULTS"
    CALLBACK_IN_PROGRESS = "CALLBACK_IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
